my_project:
   settings:
      - __inint__.py
      - dev.py
      - prod.py
   mainapp:
      - __inint__.py
      - models.py
      - views.py
      - templates:
           - mainapp:
                - base.html
                - index.html
   authapp:
      - __init__.py
      - models.py
      - views.py
      - templates:
           - mainapp:
                - base.html
                - index.html